// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/c17b1b78b886e84afe27e1b65fe5bf901da5bbe7/url-template/index.d.ts
declare module 'url-template' {
// Type definitions for url-template 2.0.6
// Project: https://github.com/bramstein/url-template
// Definitions by: Marcin Porębski <https://github.com/marcinporebski/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

var urlTemplate: UrlTemplate.TemplateParser;

export = urlTemplate;

namespace UrlTemplate
{
    interface TemplateParser {
        parse(template: string): Template;
    }

    interface Template {
        expand(parameters: any): string;
    }
}
}
